services:
  - type: web
    name: inventory-backend
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: DB_HOST
        value: YOUR_DB_HOST
      - key: DB_USER
        value: YOUR_DB_USER
      - key: DB_PASS
        value: YOUR_DB_PASS
      - key: DB_NAME
        value: YOUR_DB_NAME
      - key: JWT_SECRET
        value: your_jwt_secret
